services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  old_system:
    build:
      context: ./old-system
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  migrator:
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - database
      - old_system
    environment:
      MIGRATOR_LEGACY_SYSTEM_URL: http://old_system:5000
      MIGRATOR_DB_HOST: database
      MIGRATOR_DB_PORT: 5432
      MIGRATOR_DB_NAME: database
      MIGRATOR_DB_USERNAME: username
      MIGRATOR_DB_PASSWORD: password
volumes:
    db_data:
