CREATE SEQUENCE IF NOT EXISTS company_user_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS patient_note_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS patient_profile_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE company_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login VARCHAR(255) NOT NULL,
    CONSTRAINT company_user_pkey PRIMARY KEY (id)
);

CREATE TABLE patient_note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    legacy_guid VARCHAR(255) UNIQUE,
    created_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by_user_id BIGINT,
    last_modified_by_user_id BIGINT,
    note VARCHAR(4000),
    patient_id BIGINT NOT NULL,
    CONSTRAINT patient_note_pkey PRIMARY KEY (id)
);

CREATE TABLE patient_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    old_client_guid VARCHAR(255),
    status_id SMALLINT NOT NULL,
    CONSTRAINT patient_profile_pkey PRIMARY KEY (id)
);

ALTER TABLE company_user
ADD CONSTRAINT company_user_uniq_login UNIQUE (login);

ALTER TABLE patient_note
ADD CONSTRAINT fk_pat_note_to_modified_user FOREIGN KEY (last_modified_by_user_id) REFERENCES company_user(id) ON DELETE NO ACTION;

ALTER TABLE patient_note
ADD CONSTRAINT fk_pat_note_to_patient FOREIGN KEY (patient_id) REFERENCES patient_profile(id) ON DELETE NO ACTION;

ALTER TABLE patient_note
ADD CONSTRAINT fkpat_note_to_created_user FOREIGN KEY (created_by_user_id) REFERENCES company_user(id) ON DELETE NO ACTION;
